version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=psgre5dj@dcer1
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8882
    volumes:
      - .:/code
    ports:
      - "8882:8882"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=psgre5dj@dcer1
    depends_on:
      - db