# Generated by Django 4.0.3 on 2022-04-07 08:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('extra_information', models.TextField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('profile', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edition_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('reserach_domain_1', models.CharField(max_length=40)),
                ('reserach_domain_2', models.CharField(blank=True, max_length=40, null=True)),
                ('reserach_domain_3', models.CharField(blank=True, max_length=40, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edition_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('nacionality', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='positioning_app.institution')),
                ('tutor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='positioning_app.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edition_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tutor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='positioning_app.tutor')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
